### ISSUE TITLE
I GOT AN INTERNAL SERVER ERROR 

### ISSUE THREAD

**Issue by vishnu-the-developer** [niloyniloy/Import-Into-Database-From-Excel-File#1]
I got an inernal server error during uploading. Please Help me this is my code
`		$name = $_FILES['uploadSheet']['name'];

		$tmp_loc = $_FILES['uploadSheet']['tmp_name'];

		$extension = pathinfo($name, PATHINFO_EXTENSION);

		$new =  'file'. '.' .$extension;

		$pathAndName = "bulkUploadFiles/" . $new;

		$moveResult = move_uploaded_file($tmp_loc, $pathAndName);

			try {
				$objPHPExcel = PHPExcel_IOFactory::load($pathAndName);
			} catch(Exception $e) {
				//die('Error loading file "'.pathinfo($fileName,PATHINFO_BASENAME).'": '.$e->getMessage());
			}

			$allDataInSheet = $objPHPExcel->getActiveSheet()->toArray(null,true,true,true);

			$arrayCount = count($allDataInSheet);  // Here get total count of row in that Excel sheet

			for($i=2;$i<=$arrayCount;$i++){

                             $Sl_No= trim($allDataInSheet[$i]["A"]);

                        }`
Also i got the below code caught to be error on console
`xhr.send( ( s.hasContent && s.data ) || null );`

**Comment by niloyniloy** [comment]
pls let me know, what specific error you got. U can add those lines at the top of your code. 

```
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

or set   display_errors = on in your php.ini file.  and i think, there is nothing to do with js error. Maybe it is related to your code. This file uploading is purely server side via php. There is no js involvement here.

**Comment by vishnu-the-developer** [comment]
Thank You For Replay
​
Niloy Niloy ,

Actually this error occurred when we tried to edit an .xlsx file in Ubuntu
Libre Office. I edited it in this and saved to windows format. then I got
inernal server error. But when i saved it in .odt(linux Format). The
working is perfect. Please do keep an eye on this
Thank You

___________________________________

Thanks and Regards
*VISHNU* *S*adanandan - ASS. SOFTWARE ENGINEER
Nesote Technologies (P) Ltd.
Kaduthuruthy P.O 686604
c <https://www.facebook.com/profile.php?id=100012171632170> e
<https://plus.google.com/u/0/117426948690051127547> d
<https://twitter.com/vishnu60929848>

**Comment by niloyniloy** [comment]
thanks. I will check this up
